# Generated by Django 6.0.5 on 2026-06-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('produit', models.CharField(max_length=50)),
                ('marche', models.CharField(max_length=100)),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('prix_predit', models.FloatField()),
                ('prix_min', models.FloatField()),
                ('prix_max', models.FloatField()),
                ('tendance', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('web', 'Web'), ('sms', 'SMS'), ('api', 'API')], default='web', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Prédiction',
                'verbose_name_plural': 'Prédictions',
                'ordering': ['-date_prediction'],
            },
        ),
        migrations.CreateModel(
            name='RequeteSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=20)),
                ('message_recu', models.TextField()),
                ('message_envoye', models.TextField(blank=True)),
                ('traite', models.BooleanField(default=False)),
                ('erreur', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Requête SMS',
                'verbose_name_plural': 'Requêtes SMS',
                'ordering': ['-date_reception'],
            },
        ),
    ]
